# Remove or comment out the build command
# command = "npm run build"

# Just specify the publish directory
publish = "/"

# Keep your redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
